# Se agregan las properties propias del proyecto
#
# MS Settings.
#
ecommerce:
    base-url: api/v1

spring:
  h2:
    console: 
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:
    driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:${DB_NAME}
    #username: ${DB_USERNAME}
    #password: ${DB_PASSWORD}
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    #show-sql: true